### ISSUE TITLE
New project wizard

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#161]
New project wizard can just call `gradle init --type java-library`

see http://stackoverflow.com/questions/14017364/how-to-create-java-gradle-project

or

User Guide should recommend create Eclipse General project and run this command

**Comment by de-jcup** [comment]
# Analysis:

## Init-Plugin
The init plugin is incubating, but very long supported now:

https://docs.gradle.org/current /userguide/build_init_plugin.html
https://docs.gradle.org/2.3/userguide/build_init_plugin.html
https://docs.gradle.org/3.0/userguide/build_init_plugin.html

One problem: What gradle should we use ? Currently EGradle Setup does determine the root project
and if the gradle wrapper is used or native gradle etc.. But at this time only a native gradle would make sense, because the wrapper would init gradle wrapper too.

Pro: Works out of the box, standard
Con: This would create a dependency to a native installed gradle there. At least a check would be necessary and a dedicated user message.

## Own implementation

The wizard would simply
create a multi project structure, an own gradle standard file (maybe out of the box with libraries.gradle which is really good...) The gradle wrapper (3.0) will be copied from EGradle (check for license problems necessary)

Pro: Easy, 
Con: wrapper would be deployed with EGradle
