### ISSUE TITLE
Egradle manifest

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#18]
Hi, I am Paul Verest from @Nodeclipse 

I have Gradle IDE Pack
https://marketplace.eclipse.org/content/gradle-ide-pack
That became alternative to Eclipse Buildship Gradle Integration

I just discovered this plugin, and I wonder do you see your solution as possible to complement those 2 solutions?
Any thoughts are welcomed.

**Comment by de-jcup** [comment]
Hello Paul,

the reason why I decided to create the plugin was my personal feeling of "overloaded integration", "still not smooth working" and "two different worlds" of the current gradle integrations into eclipse.

**Thoughts about existing integrations**
I tried "Eclipse Buildship Gradle Integration" and also the pivotal springsource gradle integrations (Gradle IDE) which is part of the gradle-ide-pack

- Gradle IDE:
It has it own gradle nature and also a dedicated class container "Gradle-Dependencies" (see https://marketplace.eclipse.org/sites/default/files/Gradle-IDE-pack1.png ) which looks nice and has some advantages, but... This is not the way a standard "gradle eclipse" does, so a console call can destroy gradle-ide setups... In my team at work we have often problems with this situation (gradle works in console but not in eclipse.) and it was one of the main reasons why people decided to use intellij instead.
- Buildship: I was a little bit disappointed in this approach (I tried it but it worked not fine for me and my team)

**What does a developer REALLY need to work with gradle when you strict use KISS pattern?**
- Run /store tasks often used
- Configure environment parts (e.g. JAVA_HOME, debug mode etc.)
- Important Results have to be shown to developers in an easy access way (e.g. for BUILD FAILED, Test failed etc.)
- Use IDE and console world parallel:
 Keep as much as possible in default gradle style. Import/Synch mechansim for (existing) gradle task results (e.g. tests, eclipse settings etc.)
- An editor which supports at least syntax highlighting and maybe more powerful features
 
**Complementation possibilities**
- I think Gradle-IDE-pack could use EGradle instead of the Gradle-IDE (as an replacement)
- Maybe EGradle could use your "Minimalist Gradle Editor" instead of an own implementation (which is still very alpha). But there are some feature I would like to integrate into EGradle (e.g. hyperlinking, code template mechanism, auto completion etc.) which are not supported.
- Buildship: hmm... I think it s a complete different approach and EGradle is only a simple working replacement
