### ISSUE TITLE
While right-click Run as -> EGradle, cannot find the project

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#292]
I right-click newly checked-out egradle, select Run as -> EGRadle, 
but I cannot build this way: cannot find the project

![image](https://user-images.githubusercontent.com/1614482/30806585-08a36ab2-a229-11e7-8e26-b75265f9a1e5.png)

**Comment by paulvi** [comment]
I "changed EGradle root project",  

but now EGradleProject1 is left in error state.

![image](https://user-images.githubusercontent.com/1614482/30808334-491aca3e-a230-11e7-945d-b08850303fcd.png)

**Comment by de-jcup** [comment]
Hello @paulvi . 

1. First of all: EGradle has (at least currently) only one root project setup. In your first picture I see you got EGradleProject1 as root project defined (gradle decorator icon). But "egradle" itself is not a part inside EGradleProject1.  So when you do the "egradle --> run as ->EGradle" it is the same as would open a command shell and call "gradlew :egradle:assemble" inside "EGradle project" - there is no sub project called egradle.

2. EGradleProject1 is left in error state after switching root project. Current implemention will always hold the last errors (unpersistent) . When you execute a new gradle action from IDE, all former (old) errors will disappear.

Hmm...
I could do following:

- [ ] To solve 1. I could clean up error markers when root project changes (because no longer in charge...)
- [ ] To solve 2. I could disable "$project -> Run as -> EGradle" when $project is not inside Current egradle root folder (because then it makes no sense for $project...)

Would my two suggested solutions solve your problems/make it easier for you?

**Comment by paulvi** [comment]
I need to try it at home.
