### ISSUE TITLE
Groovy Editor

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#295]
Being amazed as how quickly Editor for Jenkinsfile #291  became reality, here is ticket for something extra large as Editor for .groovy.

Groovy-Eclipse was discontinued, and I don't know anything else.

**Comment by de-jcup** [comment]
@paulvi Thank you. EGradle is already able to

- open .groovy files (also eclipse marketplace entry has fileExtension_groovy) inside...
- show interfaces, classes etc. of groovy code also in outline / quick outline
- do syntax highlighting groovy like, groovy doc (other color on syntax highlighting)
- Special try-as approach for hyperlinking from groovy files to java or groovy classes (does use JDT + Resources) - so just hover with mouse over potential Type and press CTRL: you got a hyperlink. On pressing hyperlink a special EGradle Groovy/Java/Resource-Dialog appears where you can choose a target...

When I created the XML files for the "EGradle SDK" i was forced to inspect the origin gradle project which is written in groovy and so I stuck with editor problems... so I started  to integrate basic stuff into egradle to have at least a supporting editor when I wrote the generator parts to create the SDK info.

but...

there is still so much missing:
- Type estimation with method chaining (not really done)
- groovy JDK source integration
- code completion for groovy parts
- ...

So I would not pretend to say its really a full-stack Groovy Editor. But you can use EGradle Editor already to edit groovy files. The Jenkins Editor was simple to create because I only had to refactor EGradle core/editor so it was reuseable and also do some syntax highlighting...

So... Do you think people would need a special "Groovy Editor" which is based from EGradle and supports less/same as EGradle Editor but only with another name?

**Comment by paulvi** [comment]
Where is README or wiki/help describing editor features? ...

https://github.com/de-jcup/egradle/wiki/Features should be updated to mention basic .groovy support, this issue...

**Comment by paulvi** [comment]
https://github.com/de-jcup/egradle/blob/master/egradle-plugin-gradle-editor/plugin.xml#L40 has .groovy

**Comment by de-jcup** [comment]
I updated https://github.com/de-jcup/egradle/wiki/Features  and mentioned the basic support for .groovy files.

Hmm.. I thought again about your suggestion to create a dedicated Groovy editor based on EGradle code - maybe I should do it: 

Normally EGradle does not show a simple outline structure but always a specialized tree for gradle files  - so if I would create a "Simple Groovy editor" being part of EGradle IDE but also available standalone, I could handle the outline a little more better (e.g. like in Jenkins-Editor: just show a simple groovy antlr tree)

If it would be settled inside egradle repository and inside EGradle IDE I would not have to maintain another repository. When creating the "Simple Groovy editor" I would remove the file extension .groovy from egradles "Gradle editor".

**Comment by paulvi** [comment]
2 simpler things to consider

- first step is just add Editor for .groovy files (maybe not as IDE default) - so user can know about it
- why not having Jenkinsfile Editor inside this one repo?
