### ISSUE TITLE
Rename marketplace EGradle to EGradle IDE

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#330]
Can it help to rename https://github.com/de-jcup/egradle to EGradle IDE

Than it may be clearer that EGradle is this project, that produces EGradle Editor and EGradle IDE (with editor)

**Comment by de-jcup** [comment]
Thank you paul. I just renamed the project on marketplace. Now it has a new URL:
https://marketplace.eclipse.org/content/egradle-ide

**Comment by paulvi** [comment]
BTW, https://marketplace.eclipse.org/content/egradle will redirect correctly

**Comment by paulvi** [comment]
![image](https://user-images.githubusercontent.com/1614482/35149261-60a77cb2-fd50-11e7-8c44-ce4610e61919.png)


and Gradle IDE it has been already

**Comment by de-jcup** [comment]
Yes. I already did have the same idea about renaming to EGradle IDE and prepared it at the features site etc. already. But I hesitated to do it because of the marketplace URL rename.  When you suggested to rename I just did it ... 

It's pretty cool that https://marketplace.eclipse.org/content/egradle still works in conjuction with
https://marketplace.eclipse.org/content/egradle-ide

**Comment by paulvi** [comment]
Marketplace support for older names appear 1-2 ago
