### ISSUE TITLE
[minor] Java 9 JPMS support

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#331]
Not sure if this project can help or is it related, but it turns out, that
as of now Jan, 19th 2018, it is not trivial to build Java 9 project that is using new Java module system

Related links

https://guides.gradle.org/building-java-9-modules/
	https://github.com/gradle-guides/building-java-9-modules.git

https://docs.oracle.com/javase/tutorial/ext/basics/spi.html

https://dzone.com/articles/java-9-modules-introduction-part-1

**Comment by de-jcup** [comment]
Hmm... currently I have got no Java 9 projects which I have to build. I am aware about the module/jigsaw situation and problematic builds.

As mentinoned in
https://github.com/gradle-guides/building-java-9-modules/blob/master/contents/index.adoc 
the gradle team will adress the problem inside the origin plugins.

Maybe there could be dedicated project-wizard templates to provide improved Java9-Support. But at the moment I am extremely busy and will have no time to provide this. As you can see I did not write much changes for egradle in the last time. At least I was working a lot at bash-editor... But I will try to start writing code for EGradle in next time.

But I think I will not be able to provide a good solution here because lacking enough free time.

If you like you could create some working setup and create a template - it's very easy to implement and was designed to be customized by other developers - see https://rawgit.com/de-jcup/egradle/master/egradle-plugin-main/html/user_guide/new_project_wizard.html#custom_templates

You could contribute your template so it would be inside next release...

**Comment by paulvi** [comment]
Well, it turns out that Java 9 modules are for use with `jlink`, and cannot be used as dependencies.
https://github.com/khmarbaise/jdk9-jlink-jmod-example/issues/3#issuecomment-326771299

that makes all this JPMS as of now, not so needed for everyone.
