### ISSUE TITLE
Use local Gradle instance

### ISSUE THREAD

**Issue by paulvi** [de-jcup/egradle#332]
When creating new project, it hangs over gradle download

Please support specifiing local gradle instance in wizard

![image](https://user-images.githubusercontent.com/1614482/35159776-4cbaa046-fd76-11e7-882f-afaa9a34449e.png)

**Comment by de-jcup** [comment]
# About your problem
I think you got the problem that the download of an not already downloaded gradle wrapper does result in a timeout while intial creating the project.

# About using local gradle instances
Do you think using local gradle instances is really a good idea? In a professional environment when providing stable builds / configuration management a rebuild of an older version should be always possible with the exact same build result (which can only be provided by exact same gradle version as defined in versioned wrapper.properties).

# My current workaround
I currently do following workaround - I have had the same probem... I am executing at least one build on a console so the wrapper will be installed on my local machine. After this I am able to create all new stuff with the project wizard - the wrapper is already available...

# Suggestion for solving the problem
Would it not be better to provide a better implementation/scanning for downloading new wrapper binaries and to prevent time outs in this case? Or do you really want to use local gradle as an option inside the project wizard? Or would you prefer both options?

**Comment by paulvi** [comment]
Exactly this case, the project was created. Download took 20-30 minutes.

So the issues is about:

- download progress indicator
- wizard to have way to specify local gradle instance

**Comment by de-jcup** [comment]
A download progress indiciator would be little bit tricky - you only got indicator output on console when rich output is enabled (ASCII escape sequences for cursor movement etc.) 
This is not easy -  so I decided to create anothter issue #339 and handle only local gradle in this issue

**Comment by de-jcup** [comment]
When opening the new project wizard at the last page you can now disable gradle wrapper usage:
![image](https://user-images.githubusercontent.com/11644753/36642193-23b7dc4e-1a3c-11e8-81ec-8c4e7c65e288.png)

Just turn off the checkbox:

![image](https://user-images.githubusercontent.com/11644753/36642184-fbe2fd70-1a3b-11e8-916b-ace35005d984.png)

With enabled `gradle wrapper` pressing the `finish` button the project will be imported without another dialog. But when `gradle wrapper` is disabled after pressing `finish` the import dialog will be shown (because it's sometimes not 100% clear how to call the gradle instance - but a default OS specific setup will be proposed):
![image](https://user-images.githubusercontent.com/11644753/36642220-8a42c55a-1a3c-11e8-9ed9-fa39e65bd41a.png)

**Comment by de-jcup** [comment]
The launcher dialog showed the wrapper call type as default - should be the installed variant instead...
