### ISSUE TITLE
Single line comments not highlighted when last line is not empty.

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#403]
## Situation
This is a follow up issue from #396 - were the problem was detected:

![image](https://user-images.githubusercontent.com/11644753/155895444-148d5611-1bf4-4138-beaf-e9c5e00045ee.png)

For multi line comments it is correct:
![image](https://user-images.githubusercontent.com/11644753/155895430-4897a1b7-9568-463c-bf4a-ca0b6e4269a8.png)

## Wanted
Even when no new line at the end, the highlighting must be correct

## Solution
Change handling

**Comment by BeckerFrank** [comment]
This is caused by the use of the default Constructors for the SingleLineRule!
If you change the line
        rules.add(new SingleLineRule("//", "", groovyComment));
to
        rules.add(new SingleLineRule("//", "", groovyComment, (char) 0, true, true));
you get the correct highlighting.

This is because the default of the breaksOnEOF is set to false.
Do you want me to contribute a correction?
Or would you prefer to change this single line yourself?

**Comment by de-jcup** [comment]
@BeckerFrank : sorry... I just fixed it by myself and now I see your comment while adding this screenshot... Your were right - I did it similar... I still have not much time and I missed your comment.

With last commit I got :

![image](https://user-images.githubusercontent.com/11644753/158115593-582dff53-2046-4366-8f09-70695389d77c.png)
